"""Compile unapproved literature candidates into a non-registerable P3 review bundle.

The records in this module are deliberately distinct from formal Claim, Commit,
and Pack contracts. They preserve pending status and can never imply human approval.
The review prompt carries no source text and requests structural, scope, and
source-reference triage only. It must return needs_source_review; it cannot assess
semantic support.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import date, datetime
from pathlib import Path
from typing import Any

from gurumoji import method_experts

from . import contracts, source_ingestion

MAX_CANDIDATE_BYTES = 2 * 1024 * 1024
MAX_EXTRACTION_MANIFEST_BYTES = 1024 * 1024
MAX_EXCERPTS_BYTES = 16 * 1024 * 1024
MAX_CANDIDATES = 100
MAX_GENERATED_CANDIDATES = 1
MAX_BATCH_CANDIDATE_TEXT_CHARS = 24000
MAX_BATCH_SOURCE_OVERLAP_CHARS = 96
MAX_SOURCE_OVERLAP_TEXT_CHARS = 100000
SOURCE_OVERLAP_SHINGLE_CHARS = 8
MAX_SOURCE_SHINGLE_OCCURRENCES_PER_TEXT = 8
MAX_SOURCE_SHINGLE_INDEX_POSITIONS = 64
P3_EXPERT_ID = "exp-framework-method"
P3_SOURCE_ID = "LIT-gale-2013-framework"
PROMPT_RENDERER_VERSION = "p3-candidate-review-v1"
GALE_PDF_PAGE = 4
GALE_PRINTED_PAGE = 3
GALE_ANCHOR_ID = "p-000004"
LOCAL_MODEL_ID = "qwen/qwen3-8b"
REVIEW_PROMPT_TEMPLATE = (
    "Internal P3 source-reference triage only for {expert_id}. This is not a production prompt. "
    "Do not decide whether candidate claims are semantically supported, true, or approved. "
    "The source text is absent. Inspect source references and scope only; always return status "
    "needs_source_review and leave every candidate pending human source review. Codex checks are not approval.\n\n"
    "[TRIAGE_INPUT_JSON]\n{payload_json}"
).encode("utf-8")
GENERATION_PROMPT_TEMPLATE = (
    "/no_think\nCreate exactly one draft-only atomic candidate for the named expert using only the supplied source excerpt. "
    "This candidate must describe the inductive approach only, limited to open coding followed by subsequent "
    "theme refinement. Do not state or imply that the entire analysis is without prior constraints. "
    "This is a source-faithfulness task, not an opportunity to improve or generalize the method. Preserve every "
    "logical connector and quantifier exactly: AND stays AND, OR stays OR, and necessary, sufficient, "
    "conditional, and alternative conditions must not change. Keep alternatives conditional when the source "
    "does. Do not add data-type restrictions, populations, thresholds, prerequisites, or exceptions absent from "
    "the source. Claims, applicability, and exceptions must come only from SOURCE_EXCERPT. The expert task context "
    "contains only an ID and title: never generate operational ExpertCatalog applicability checks, prohibited "
    "conclusions, checklists, or requirements. In every output field, never reproduce any source substring of "
    "48 or more consecutive characters; paraphrase instead. List an exception only when the excerpt explicitly states it. "
    "Do not turn an interpretation into an explicit source claim. In evidence_basis, begin with `[source-explicit]` "
    "for a directly stated point or `[inference]` for a clearly tentative interpretation, then include a concise "
    "paraphrase of the specific excerpt content that supports the candidate. Preserve its distinctions and quantifiers "
    "while paraphrasing; do not quote. A bare label is invalid. "
    "Keep the single atomic claim under 35 words. Keep evidence_basis under 20 words and paraphrase; "
    "never quote a sentence. Prefer fewer candidates over unsupported detail. Do not claim approval, certainty, "
    "or completed source review. "
    "Return one JSON object with exactly one `candidates` array. Each candidate object must contain exactly "
    "`claim` (string), `applicability` (array of strings), `exceptions` (array of strings), `claim_type` "
    "(exactly `decision_rule` or `limitation`), and `evidence_basis` (string). Do not use any other claim_type. "
    "No source IDs, page numbers, or hashes are generated by you; the caller binds these from the verified request.\n\n"
    "REQUEST_JSON:\n{request_json}\n\nSOURCE_EXCERPT:\n{source_text}"
).encode("utf-8")
GENERATION_PROMPT_TEMPLATE_PREVIOUS = (
    "Create a small draft-only knowledge candidate batch for the named expert. Use the supplied one-page "
    "licensed source excerpt and scope. Paraphrase; do not quote long verbatim text. Do not claim approval, "
    "certainty, or completed source review. Return only candidate statements, applicability, exceptions, "
    "candidate_type (decision_rule or limitation), and a concise rationale. No source IDs, page numbers, "
    "or hashes are generated by you; the caller binds these from the verified request.\n\n"
    "REQUEST_JSON:\n{request_json}\n\nSOURCE_EXCERPT:\n{source_text}"
).encode("utf-8")
CANDIDATE_RESPONSE_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["candidates"],
    "properties": {
        "candidates": {
            "type": "array",
            "minItems": 1,
            "maxItems": MAX_GENERATED_CANDIDATES,
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["claim", "applicability", "exceptions", "claim_type", "evidence_basis"],
                "properties": {
                    "claim": {"type": "string", "minLength": 1, "maxLength": 300},
                    "applicability": {"type": "array", "maxItems": 10,
                                      "items": {"type": "string", "maxLength": 300}},
                    "exceptions": {"type": "array", "maxItems": 10,
                                   "items": {"type": "string", "maxLength": 300}},
                    "claim_type": {"type": "string", "enum": ["decision_rule", "limitation"]},
                    "evidence_basis": {"type": "string", "minLength": 1, "maxLength": 180},
                },
            },
        },
    },
}


def _render_generation_prompt(request_descriptor: dict, source_text: str,
                              template: bytes = GENERATION_PROMPT_TEMPLATE) -> str:
    return template.decode("utf-8").format(
        request_json=contracts.canonical_json(request_descriptor).decode("utf-8"),
        source_text=source_text)


def _model_task_context(expert_scope: dict) -> dict:
    if not isinstance(expert_scope, dict) or not isinstance(expert_scope.get("expert_id"), str) or not isinstance(
            expert_scope.get("title"), str):
        _fail("expert task context is invalid")
    return {"expert_id": expert_scope["expert_id"], "expert_title": expert_scope["title"]}


class CandidatePipelineError(ValueError):
    """A pending candidate or its provenance failed closed validation."""


def _fail(reason: str) -> None:
    raise CandidatePipelineError(reason)


def _contains_local_path(value: str) -> bool:
    lowered = value.casefold()
    if re.search(r"(?i)\bfile:", value):
        return True
    if "\\" in value or value.startswith("//"):
        return True
    if value.startswith("\\"):
        return True
    # Absolute and drive-relative Windows paths, plus absolute POSIX paths.
    if re.search(r"(?<![A-Za-z0-9])[A-Za-z]:(?:[\\/]|[^\s,;]+)", value):
        return True
    if re.search(r"(?<![A-Za-z0-9])~(?:[A-Za-z0-9_.-]+)?(?:[/\\]|$)", value):
        return True
    if re.search(r"(?<![A-Za-z0-9:/])/(?!/)[^\s,;]+", value):
        return True
    normalized = value.replace("\\", "/")
    return any(token in normalized.casefold() for token in
               ("/users/", "/home/", "/tmp/", "/private/", "/mnt/", "/var/"))


def _normalized_source_texts(source_texts: list[str]) -> list[str]:
    normalized_texts = []
    seen = set()
    total_chars = 0
    for source_text in source_texts:
        normalized_source = "".join(character for character in source_text.casefold()
                                    if character.isalnum())
        total_chars += len(normalized_source)
        if total_chars > MAX_SOURCE_OVERLAP_TEXT_CHARS:
            _fail("source text exceeds the bounded overlap-check size")
        if normalized_source not in seen:
            normalized_texts.append(normalized_source)
            seen.add(normalized_source)
    return normalized_texts


def _source_overlap_ngrams(source_texts: list[str], width: int = 48) -> set[str]:
    grams = set()
    for normalized_source in _normalized_source_texts(source_texts):
        grams.update(normalized_source[position:position + width]
                     for position in range(len(normalized_source) - width + 1))
    return grams


def _contains_source_overlap(value: str, source_ngrams: set[str], width: int = 48) -> bool:
    normalized_candidate = "".join(character for character in value.casefold() if character.isalnum())
    return any(normalized_candidate[position:position + width] in source_ngrams
               for position in range(len(normalized_candidate) - width + 1))


def _validate_candidate_text(value: Any, name: str, source_texts: list[str], limit: int,
                             *, source_ngrams: set[str] | None = None,
                             candidate_index: int | None = None) -> str:
    try:
        text = contracts._text(value, name, max_length=limit)
    except contracts.ContractError:
        _fail("candidate text is invalid")
    if _contains_local_path(text):
        _fail("candidate contains a local path")
    source_ngrams = source_ngrams if source_ngrams is not None else _source_overlap_ngrams(source_texts)
    if _contains_source_overlap(text, source_ngrams):
        item = "unknown" if candidate_index is None else str(candidate_index)
        _fail(f"candidate source overlap (candidate_index={item}; field={name}; "
              "longest_overlap_chars_at_least=48)")
    return text


def _validate_aggregate_candidate_source_overlap(values: list[str], source_ngrams: set[str],
                                                 candidate_index: int) -> None:
    # Remove whitespace and punctuation so source fragments cannot evade the
    # contiguous check by being split across fields or joined with delimiters.
    candidate_text = "".join(value for value in values)
    if _contains_source_overlap(candidate_text, source_ngrams):
        _fail(f"candidate aggregate source overlap (candidate_index={candidate_index}; "
              "longest_overlap_chars_at_least=48)")


def _validate_batch_source_overlap(candidate_values: list[list[str]], source_texts: list[str]) -> None:
    """Reject substantial verbatim Source material split across fields or candidates."""
    shingle_size = SOURCE_OVERLAP_SHINGLE_CHARS
    normalized_sources = _normalized_source_texts(source_texts)
    covered_source_chars = 0
    positions_by_shingle: dict[str, list[tuple[int, int]]] = {}
    for source_index, normalized_source in enumerate(normalized_sources):
        if len(normalized_source) < shingle_size:
            continue
        source_positions_by_shingle: dict[str, list[int]] = {}
        for source_position in range(len(normalized_source) - shingle_size + 1):
            shingle = normalized_source[source_position:source_position + shingle_size]
            source_positions_by_shingle.setdefault(shingle, []).append(source_position)
        for shingle, source_positions in source_positions_by_shingle.items():
            if len(source_positions) > MAX_SOURCE_SHINGLE_OCCURRENCES_PER_TEXT:
                continue
            indexed_positions = positions_by_shingle.setdefault(shingle, [])
            remaining = MAX_SOURCE_SHINGLE_INDEX_POSITIONS - len(indexed_positions)
            if remaining > 0:
                indexed_positions.extend((source_index, position)
                                          for position in source_positions[:remaining])
    if not positions_by_shingle:
        return

    source_coverage = [bytearray(len(source)) for source in normalized_sources]
    candidate_segments = [
        "".join(character for character in value.casefold() if character.isalnum())
        for values in candidate_values for value in values
    ]
    candidate_text = "\x00".join(candidate_segments)
    for candidate_position in range(len(candidate_text) - shingle_size + 1):
        shingle = candidate_text[candidate_position:candidate_position + shingle_size]
        if "\x00" in shingle:
            continue
        for source_index, source_position in positions_by_shingle.get(shingle, ()):
            end = source_position + shingle_size
            coverage = source_coverage[source_index]
            newly_covered = coverage[source_position:end].count(0)
            if newly_covered:
                coverage[source_position:end] = b"\x01" * shingle_size
                covered_source_chars += newly_covered
                if covered_source_chars >= MAX_BATCH_SOURCE_OVERLAP_CHARS:
                    _fail("candidate batch contains cumulative verbatim Source fragments")


def _normalize_generated_candidate(row: Any) -> dict:
    """Accept only the canonical schema or the one observed closed alias schema."""
    if not isinstance(row, dict):
        _fail("generated candidate must be an object")
    canonical = {"claim", "applicability", "exceptions", "claim_type", "evidence_basis"}
    observed_alias = {"candidate_statement", "applicability", "exceptions",
                      "candidate_type", "rationale"}
    keys = set(row)
    if keys == canonical:
        contracts._object(row, canonical, name="generated candidate")
        return row
    if keys == observed_alias:
        return {
            "claim": row["candidate_statement"],
            "applicability": row["applicability"],
            "exceptions": row["exceptions"],
            "claim_type": row["candidate_type"],
            "evidence_basis": row["rationale"],
        }
    _fail("generated candidate fields do not match a supported closed schema")


def _read_limited(path: Path, maximum: int) -> bytes:
    if path.is_symlink() or not path.is_file():
        _fail("input artifact is unavailable")
    try:
        size = path.stat().st_size
        if size < 0 or size > maximum:
            _fail("input artifact exceeds the size limit")
        with path.open("rb") as stream:
            data = stream.read(maximum + 1)
    except OSError:
        _fail("input artifact could not be read")
    if len(data) != size or len(data) > maximum:
        _fail("input artifact changed while being read")
    return data


def _json_file(path: Path, maximum: int, *, canonical: bool = False) -> tuple[dict, bytes]:
    raw = _read_limited(path, maximum)
    try:
        value = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        _fail("input JSON is invalid")
    if not isinstance(value, dict):
        _fail("input JSON must be an object")
    if canonical and contracts.canonical_json(value) != raw:
        _fail("input JSON is not canonical")
    try:
        contracts._reject_answer_material(value)
    except contracts.ContractError:
        _fail("evaluation-private material is not allowed")
    return value, raw


def _json_safe(value: Any) -> Any:
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    _fail("base expert definition contains an unsupported value")


def _definition_bytes(definition: dict) -> bytes:
    try:
        contracts._reject_answer_material(definition)
        return contracts.canonical_json(_json_safe(definition))
    except contracts.ContractError:
        _fail("base expert definition is invalid")


def _load_base_expert(expert_id: str) -> tuple[dict, str]:
    if expert_id != P3_EXPERT_ID:
        _fail("this P3 prototype is pinned to the Framework Method expert")
    with tempfile.TemporaryDirectory(prefix="gurumoji-p3-empty-local-") as empty_local:
        catalog = method_experts.ExpertCatalog(
            root=method_experts.SOFTWARE_ROOT, local_root=empty_local)
        entries = catalog.index()
        entry = entries.get(expert_id)
        if not entry or entry.get("source") != "base":
            _fail("pinned base expert definition is unavailable")
        try:
            definition = catalog.definition(expert_id)
        except Exception:
            _fail("pinned base expert definition failed validation")
    return definition, hashlib.sha256(_definition_bytes(definition)).hexdigest()


def _load_excerpt_index(path: Path) -> dict[str, dict]:
    raw = _read_limited(path, MAX_EXCERPTS_BYTES)
    if not raw.endswith(b"\n"):
        _fail("source excerpt artifact is incomplete")
    index: dict[str, dict] = {}
    for line in raw.splitlines():
        if not line:
            _fail("source excerpt artifact contains an empty row")
        try:
            record = json.loads(line.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError):
            _fail("source excerpt artifact is invalid")
        if not isinstance(record, dict) or contracts.canonical_json(record) != line:
            _fail("source excerpt row is not canonical")
        contracts._reject_answer_material(record)
        text = record.get("text")
        text_hash = record.get("extracted_text_sha256")
        try:
            contracts._text(text, "extracted text", max_length=200_000)
            contracts._hash(text_hash, "extracted_text_sha256")
        except contracts.ContractError:
            _fail("source excerpt row is invalid")
        if hashlib.sha256(text.encode("utf-8")).hexdigest() != text_hash or text_hash in index:
            _fail("source excerpt hash or uniqueness check failed")
        locations = record.get("locations")
        if (not isinstance(locations, list) or not locations or
                any(not isinstance(item, str) for item in locations) or len(set(locations)) != len(locations)):
            _fail("source excerpt locations are invalid")
        index[text_hash] = {"locations": set(locations), "text": text}
    if not index:
        _fail("source extraction contains no excerpt records")
    return index


def _validate_batch(batch: dict, source_texts: list[str], *,
                    expected_source_manifest_sha256: str,
                    expected_expert_definition_sha256: str,
                    expected_expert_scope: dict) -> list[dict]:
    required = {
        "kind", "schema_version", "source_id", "source_version", "source_sha256",
        "authority_note_sha256", "source_manifest_sha256", "expert_id", "expert_definition_version",
        "expert_definition_sha256", "generation_request_sha256", "generation_prompt_template_sha256",
        "generation_prompt_sha256", "generation_request_record", "generator", "review_status", "source_anchor", "candidates",
        "promotion_gate",
    }
    contracts._object(batch, required, name="candidate batch")
    if batch["kind"] != "unapproved_knowledge_candidate_batch" or batch["schema_version"] != 1:
        _fail("candidate batch type or version is unsupported")
    if batch["source_id"] != P3_SOURCE_ID or batch["expert_id"] != P3_EXPERT_ID:
        _fail("candidate batch is outside the bounded P3 prototype")
    try:
        contracts._text(batch["source_version"], "source_version", max_length=500)
        for key in ("source_sha256", "authority_note_sha256", "source_manifest_sha256",
                    "expert_definition_sha256", "generation_request_sha256",
                    "generation_prompt_template_sha256", "generation_prompt_sha256"):
            contracts._hash(batch[key], key)
        if type(batch["expert_definition_version"]) is not int or batch["expert_definition_version"] < 1:
            raise contracts.ContractError("definition version is invalid")
    except contracts.ContractError:
        _fail("candidate batch provenance is invalid")
    if (batch["source_manifest_sha256"] != expected_source_manifest_sha256 or
            batch["expert_definition_sha256"] != expected_expert_definition_sha256):
        _fail("candidate generation pins do not match current inputs")
    template_by_hash = {
        hashlib.sha256(template).hexdigest(): template
        for template in (GENERATION_PROMPT_TEMPLATE, GENERATION_PROMPT_TEMPLATE_PREVIOUS)
    }
    generation_template = template_by_hash.get(batch["generation_prompt_template_sha256"])
    if generation_template is None:
        _fail("candidate generation template hash is not the pinned template")
    request_record = batch["generation_request_record"]
    contracts._object(request_record, {"kind", "schema_version", "model_id", "model_route", "temperature",
                                       "max_tokens", "expert_definition_sha256", "expert_scope",
                                       "source_binding", "prompt_template_sha256",
                                       "response_schema_sha256", "rendered_prompt_sha256"},
                      name="generation request record")
    try:
        contracts._hash(request_record["expert_definition_sha256"], "request expert definition hash")
        contracts._hash(request_record["prompt_template_sha256"], "request prompt template hash")
        contracts._hash(request_record["response_schema_sha256"], "request response schema hash")
        contracts._hash(request_record["rendered_prompt_sha256"], "request rendered prompt hash")
    except contracts.ContractError:
        _fail("generation request hash record is invalid")
    if (request_record["kind"] != "local_candidate_generation_request" or
            request_record["schema_version"] != 1 or request_record["model_id"] != LOCAL_MODEL_ID or
            request_record["model_route"] != "local" or request_record["temperature"] != 0.1 or
            request_record["max_tokens"] != 1400 or
            request_record["expert_definition_sha256"] != batch["expert_definition_sha256"] or
            request_record["prompt_template_sha256"] != batch["generation_prompt_template_sha256"] or
            request_record["response_schema_sha256"] != contracts.sha256_json(CANDIDATE_RESPONSE_SCHEMA) or
            contracts.sha256_json(request_record) != batch["generation_request_sha256"]):
        _fail("generation request record does not match candidate provenance")
    request_source = request_record["source_binding"]
    contracts._object(request_source, {"source_id", "source_version", "source_sha256",
                                       "source_manifest_sha256", "authority_note_sha256", "anchor_id",
                                       "pdf_page", "printed_page", "extracted_text_sha256"},
                      name="generation source binding")
    request_scope = request_record["expert_scope"]
    if not isinstance(request_scope, dict) or request_scope != expected_expert_scope:
        _fail("generation request expert scope is invalid")
    if (request_source.get("anchor_id") != GALE_ANCHOR_ID or
            request_source.get("pdf_page") != GALE_PDF_PAGE or
            request_source.get("printed_page") != GALE_PRINTED_PAGE or
            request_source.get("source_manifest_sha256") != batch["source_manifest_sha256"] or
            request_source.get("authority_note_sha256") != batch["authority_note_sha256"] or
            request_source.get("source_id") != batch["source_id"] or
            request_source.get("source_version") != batch["source_version"] or
            request_source.get("source_sha256") != batch["source_sha256"]):
        _fail("generation request Source binding does not match candidate provenance")
    batch_anchor = batch.get("source_anchor")
    if (not isinstance(batch_anchor, dict) or
            request_source.get("extracted_text_sha256") != batch_anchor.get("extracted_text_sha256")):
        _fail("generation request anchor hash differs from candidate anchor")
    matching_texts = [text for text in source_texts
                      if hashlib.sha256(text.encode("utf-8")).hexdigest() ==
                      request_source.get("extracted_text_sha256")]
    if len(matching_texts) != 1:
        _fail("generation request does not bind one verified source excerpt")
    descriptor = {key: value for key, value in request_record.items()
                  if key != "rendered_prompt_sha256"}
    rendered_prompt = _render_generation_prompt(_model_task_context(request_scope), matching_texts[0],
                                                generation_template)
    expected_rendered_hash = hashlib.sha256(rendered_prompt.encode("utf-8")).hexdigest()
    if (request_record["rendered_prompt_sha256"] != expected_rendered_hash or
            batch["generation_prompt_sha256"] != expected_rendered_hash):
        _fail("rendered generation prompt hash does not match pinned inputs")
    if batch["review_status"] != "pending_human_review":
        _fail("candidate batch is not explicitly pending human review")

    generator = batch["generator"]
    contracts._object(generator, {"model", "runtime", "prompt_tokens", "completion_tokens", "total_tokens",
                                  "elapsed_seconds", "finish_reason", "temperature"}, name="generator")
    if generator["model"] != LOCAL_MODEL_ID or generator["runtime"] != "LM Studio loopback on local RTX 5070":
        _fail("candidate generator metadata is not the pinned local runtime")
    if generator["finish_reason"] != "stop":
        _fail("candidate generation did not stop cleanly")
    for field in ("prompt_tokens", "completion_tokens", "total_tokens"):
        if type(generator[field]) is not int or generator[field] < 0:
            _fail("candidate generator token counts are invalid")
    if generator["total_tokens"] != generator["prompt_tokens"] + generator["completion_tokens"]:
        _fail("candidate generator token counts do not add up")
    if (isinstance(generator["elapsed_seconds"], bool) or
            not isinstance(generator["elapsed_seconds"], (int, float)) or generator["elapsed_seconds"] < 0):
        _fail("candidate generator elapsed time is invalid")
    temperature = generator["temperature"]
    if isinstance(temperature, bool) or not isinstance(temperature, (int, float)) or not 0 <= temperature <= 2:
        _fail("candidate generator temperature is invalid")

    gate = batch["promotion_gate"]
    contracts._object(gate, {"formal_claim_created", "approved_for_expert_pack", "reason"}, name="promotion gate")
    if gate["formal_claim_created"] is not False or gate["approved_for_expert_pack"] is not False:
        _fail("candidate batch claims a promotion that has not occurred")
    contracts._text(gate["reason"], "promotion reason", max_length=2000)
    anchor = batch["source_anchor"]
    contracts._object(anchor, {"anchor_id", "pdf_page", "printed_page", "extracted_text_sha256"}, name="source anchor")
    try:
        contracts._id(anchor["anchor_id"], "anchor_id")
        contracts._hash(anchor["extracted_text_sha256"], "extracted_text_sha256")
        for field in ("pdf_page", "printed_page"):
            if type(anchor[field]) is not int or anchor[field] < 1:
                raise contracts.ContractError("page must be positive")
    except contracts.ContractError:
        _fail("candidate batch source anchor is invalid")
    if (anchor["anchor_id"] != GALE_ANCHOR_ID or anchor["pdf_page"] != GALE_PDF_PAGE or
            anchor["printed_page"] != GALE_PRINTED_PAGE):
        _fail("Gale page mapping is not the verified PDF page 4 to printed page 3 mapping")

    candidates = batch["candidates"]
    if not isinstance(candidates, list) or not 1 <= len(candidates) <= MAX_CANDIDATES:
        _fail("candidate count is invalid")
    if (batch["generation_prompt_template_sha256"] == hashlib.sha256(GENERATION_PROMPT_TEMPLATE).hexdigest()
            and len(candidates) != MAX_GENERATED_CANDIDATES):
        _fail("targeted P3 batch must contain exactly one candidate")
    candidate_ids = set()
    candidate_overlap_values = []
    batch_overlap_values = []
    source_ngrams = _source_overlap_ngrams(source_texts)
    batch_candidate_text_chars = 0
    for candidate_index, candidate in enumerate(candidates, start=1):
        contracts._object(candidate, {"candidate_id", "claim", "applicability", "exceptions", "claim_type",
                                      "evidence_basis"}, name="candidate item")
        try:
            contracts._id(candidate["candidate_id"], "candidate_id")
        except contracts.ContractError:
            _fail("candidate item ID is invalid")
        if candidate["candidate_id"] in candidate_ids:
            _fail("candidate IDs must be unique")
        candidate_ids.add(candidate["candidate_id"])
        if candidate["claim_type"] not in {"decision_rule", "limitation"}:
            safe_value = json.dumps(candidate["claim_type"], ensure_ascii=True, separators=(",", ":"))
            if len(safe_value) > 80:
                safe_value = safe_value[:77] + "..."
            _fail(f"candidate claim_type unsupported: {safe_value}")
        claim = _validate_candidate_text(candidate["claim"], "claim", source_texts, 300,
                                         source_ngrams=source_ngrams,
                                         candidate_index=candidate_index)
        evidence_basis = _validate_candidate_text(candidate["evidence_basis"], "evidence_basis", source_texts,
                                                  180, source_ngrams=source_ngrams,
                                                  candidate_index=candidate_index)
        aggregate_values = [claim, evidence_basis]
        if batch["generation_prompt_template_sha256"] == hashlib.sha256(GENERATION_PROMPT_TEMPLATE).hexdigest():
            if evidence_basis.startswith("[source-explicit]"):
                supporting_text = evidence_basis[len("[source-explicit]"):].strip()
            elif evidence_basis.startswith("[inference]"):
                supporting_text = evidence_basis[len("[inference]"):].strip()
            else:
                _fail("current candidate evidence basis must distinguish source text from inference")
            if len(supporting_text) < 12:
                _fail("current candidate evidence basis requires a concise supporting paraphrase")
            if len(claim.split()) > 35:
                _fail(f"candidate word limit exceeded (candidate_index={candidate_index}; field=claim)")
            if len(supporting_text.split()) > 19:
                _fail(f"candidate word limit exceeded (candidate_index={candidate_index}; field=evidence_basis)")
            if any(mark in claim or mark in evidence_basis for mark in ('"', "“", "”")):
                _fail(f"candidate contains quotation marks (candidate_index={candidate_index})")
        for field in ("applicability", "exceptions"):
            value = candidate[field]
            if not isinstance(value, list) or len(value) > 10:
                _fail("candidate scope lists are invalid")
            for item_index, item in enumerate(value):
                aggregate_values.append(_validate_candidate_text(
                    item, f"{field}[{item_index}]", source_texts, 300,
                    source_ngrams=source_ngrams,
                    candidate_index=candidate_index))
        if sum(len(value) for value in aggregate_values) > 2400:
            _fail(f"candidate aggregate text exceeds the size limit (candidate_index={candidate_index})")
        _validate_aggregate_candidate_source_overlap(aggregate_values, source_ngrams, candidate_index)
        candidate_overlap_values.append(aggregate_values)
        batch_overlap_values.extend(aggregate_values)
        batch_candidate_text_chars += sum(len(value) for value in aggregate_values)
        if batch_candidate_text_chars > MAX_BATCH_CANDIDATE_TEXT_CHARS:
            _fail("candidate batch aggregate text exceeds the size limit")
    _validate_aggregate_candidate_source_overlap(batch_overlap_values, source_ngrams, 0)
    _validate_batch_source_overlap(candidate_overlap_values, source_texts)
    return candidates


def _build_bundle(batch: dict, batch_bytes: bytes, source_manifest: dict,
                  extraction_dir: Path, definition: dict, definition_sha256: str,
                  note_sha256: str, trusted_source: dict, trusted_review: dict) -> dict:
    try:
        contracts._hash(source_manifest["manifest_sha256"], "manifest_sha256")
    except (KeyError, contracts.ContractError):
        _fail("source extraction manifest lacks its own hash")
    unsigned_source_manifest = {key: item for key, item in source_manifest.items()
                                if key != "manifest_sha256"}
    if contracts.sha256_json(unsigned_source_manifest) != source_manifest["manifest_sha256"]:
        _fail("source extraction manifest hash mismatch")
    if batch.get("source_manifest_sha256") != source_manifest["manifest_sha256"]:
        _fail("candidate was generated from a different source extraction manifest")
    if source_manifest.get("kind") != "private_source_extraction" or source_manifest.get("storage_class") != "private_local_only":
        _fail("source extraction manifest is not a private local extraction")
    try:
        manifest_source = contracts.validate_source(source_manifest["source"])
    except (KeyError, contracts.ContractError):
        _fail("source extraction manifest has an invalid Source")
    if manifest_source["locator"]["kind"] == "local_uri":
        _fail("local locators are not allowed in a candidate bundle")
    source_authority_without_anchors = {key: value for key, value in trusted_source.items() if key != "anchors"}
    manifest_source_without_anchors = {key: value for key, value in manifest_source.items() if key != "anchors"}
    if (manifest_source_without_anchors != source_authority_without_anchors
            or source_manifest.get("rights_review") != trusted_review):
        _fail("extraction Source or rights review differs from current Software Vault authority")
    source = contracts.validate_source({**trusted_source, "anchors": manifest_source["anchors"]})
    if (source["source_id"] != batch["source_id"] or source["version"] != batch["source_version"]
            or source["sha256"] != batch["source_sha256"]
            or source_manifest.get("original_sha256") != source["sha256"]
            or source_manifest.get("authority_note_sha256") != batch["authority_note_sha256"]
            or source_manifest["authority_note_sha256"] != note_sha256
            or source["rights"]["allowed_routes"] != ["local"]
            or source["access_scope"] != "full_text"):
        _fail("candidate batch does not match the current private Source authority")
    excerpt_index = _load_excerpt_index(extraction_dir / "excerpts.jsonl")
    candidates = _validate_batch(batch, [record["text"] for record in excerpt_index.values()],
                                 expected_source_manifest_sha256=source_manifest["manifest_sha256"],
                                 expected_expert_definition_sha256=definition_sha256,
                                 expected_expert_scope={key: definition[key] for key in
                                     ("expert_id", "definition_version", "title", "scope", "out_of_scope",
                                      "required_inputs", "applicability_checks", "prohibited_conclusions")})
    source_anchor = batch["source_anchor"]
    anchor = next((item for item in source["anchors"] if item["anchor_id"] == source_anchor["anchor_id"]), None)
    if (anchor is None or anchor["kind"] != "page"
            or anchor["start"] != str(source_anchor["pdf_page"])
            or anchor["end"] != str(source_anchor["pdf_page"])
            or anchor["extracted_text_sha256"] != source_anchor["extracted_text_sha256"]):
        _fail("candidate anchor does not match the extraction manifest")
    excerpt_record = excerpt_index.get(anchor["extracted_text_sha256"])
    if excerpt_record is None or anchor["anchor_id"] not in excerpt_record["locations"]:
        _fail("candidate anchor is not present in the extracted excerpt index")

    restrictions = source["rights"]
    candidate_claims = []
    for candidate in candidates:
        candidate_claims.append({
            "kind": "candidate_claim",
            "schema_version": 1,
            "candidate_id": candidate["candidate_id"],
            "claim": candidate["claim"],
            "applicability": candidate["applicability"],
            "exceptions": candidate["exceptions"],
            "candidate_type": candidate["claim_type"],
            "review_status": "pending_human_review",
            "evidence_basis": candidate["evidence_basis"],
            "evidence": [{
                "source_id": source["source_id"], "source_version": source["version"],
                "source_sha256": source["sha256"], "anchor_id": anchor["anchor_id"],
                "span": {"kind": anchor["kind"], "start": anchor["start"], "end": anchor["end"]},
                "extracted_text_sha256": anchor["extracted_text_sha256"],
                "reported_printed_page": source_anchor["printed_page"],
            }],
            "rights": restrictions,
            "provenance": {
                "candidate_batch_sha256": hashlib.sha256(batch_bytes).hexdigest(),
                "authority_note_sha256": note_sha256,
                "source_manifest_sha256": source_manifest["manifest_sha256"],
                "expert_definition_sha256": definition_sha256,
                "generator": batch["generator"],
                "codex_review_is_human_approval": False,
            },
        })

    expert_projection = {
        "expert_id": definition["expert_id"],
        "definition_version": definition["definition_version"],
        "title": definition["title"], "role": definition["role"],
        "scope": definition["scope"], "out_of_scope": definition["out_of_scope"],
        "required_inputs": definition["required_inputs"],
        "applicability_checks": definition["applicability_checks"],
        "prohibited_conclusions": definition["prohibited_conclusions"],
        "ai_assist_brief": definition["ai_assist"]["brief"],
    }
    pack_input = {
        "kind": "p3_non_release_candidate_pack_input",
        "schema_version": 1,
        "stage": "candidate_pending_human_review",
        "release_eligible": False,
        "registerable_as_pack": False,
        "expert": expert_projection,
        "expert_definition_sha256": definition_sha256,
        "source": source,
        "candidate_claims": candidate_claims,
        "input_provenance": {
            "candidate_batch_sha256": hashlib.sha256(batch_bytes).hexdigest(),
            "source_manifest_sha256": source_manifest["manifest_sha256"],
            "authority_note_sha256": note_sha256,
            "expert_definition_sha256": definition_sha256,
            "generation_request_sha256": batch["generation_request_sha256"],
            "generation_prompt_template_sha256": batch["generation_prompt_template_sha256"],
            "generation_prompt_sha256": batch["generation_prompt_sha256"],
        },
    }
    pack_input["candidate_input_sha256"] = contracts.sha256_json(pack_input)

    prompt_payload = {
        "expert": expert_projection,
        "candidate_claims": candidate_claims,
        "source_citation": {key: source[key] for key in
                             ("source_id", "version", "sha256", "title", "authors", "publication_year",
                              "locator", "license", "license_url", "adaptation_notice") if key in source},
        "source_anchor": {key: anchor[key] for key in ("anchor_id", "kind", "start", "end",
                                                         "extracted_text_sha256")},
    }
    prompt = REVIEW_PROMPT_TEMPLATE.decode("utf-8").format(
        expert_id=P3_EXPERT_ID, payload_json=contracts.canonical_json(prompt_payload).decode("utf-8"))
    prompt_record = {
        "kind": "internal_candidate_review_prompt",
        "renderer_version": PROMPT_RENDERER_VERSION,
        "usage": "review_only_not_runtime",
        "required_status": "needs_source_review",
        "prompt_template_sha256": hashlib.sha256(REVIEW_PROMPT_TEMPLATE).hexdigest(),
        "prompt_sha256": hashlib.sha256(prompt.encode("utf-8")).hexdigest(),
        "expert_definition_sha256": definition_sha256,
        "candidate_input_sha256": pack_input["candidate_input_sha256"],
        "prompt": prompt,
    }
    bundle = {
        "kind": "p3_candidate_review_bundle",
        "schema_version": 1,
        "stage": "internal_candidate_only",
        "release_eligible": False,
        "registered_pack": False,
        "candidate_pack_input": pack_input,
        "expert_prompt": prompt_record,
    }
    bundle["bundle_sha256"] = contracts.sha256_json(bundle)
    return bundle


def compile_candidate_review_bundle(candidate_batch_path: str | Path,
                                   source_extraction_dir: str | Path,
                                   output_path: str | Path) -> dict:
    """Build an explicit, deterministic, non-release P3 bundle from local inputs.

    Output must be outside the repository and source extraction directory. The
    bundle contains no extracted source text and cannot be registered as a Pack.
    """
    requested_candidate = Path(candidate_batch_path).expanduser().absolute()
    if requested_candidate.is_symlink():
        _fail("candidate input may not be a symbolic link")
    candidate_path = requested_candidate.resolve(strict=True)
    extraction_path = Path(source_extraction_dir).expanduser().resolve(strict=True)
    destination = Path(output_path).expanduser().absolute()
    repository_root = Path(__file__).resolve().parents[3]
    destination_resolved = destination.resolve(strict=False)
    if (not extraction_path.is_dir() or extraction_path.is_symlink()
            or not destination_resolved.parent.exists()
            or destination_resolved.is_relative_to(repository_root)
            or destination_resolved.is_relative_to(extraction_path)):
        _fail("candidate output location is not an approved external staging path")
    batch, batch_bytes = _json_file(candidate_path, MAX_CANDIDATE_BYTES)
    manifest, _manifest_bytes = _json_file(extraction_path / "manifest.json",
                                            MAX_EXTRACTION_MANIFEST_BYTES, canonical=True)
    if manifest.get("manifest_sha256") is None:
        _fail("source extraction manifest is incomplete")
    note_path = (source_ingestion.SOFTWARE_VAULT_ROOT / "50-Analysis-Methods" / "20-Literature"
                 / f"{P3_SOURCE_ID}.md")
    authoritative_source, rights_review, note_sha256 = source_ingestion._trusted_source_authority(P3_SOURCE_ID)
    properties, _checked_note_sha256 = source_ingestion._frontmatter(note_path)
    if (properties.get("status") != "current" or properties.get("correction_status") != "none_found"
            or properties.get("rights_review_status") != "approved"
            or properties.get("llm_processing_permission") != "explicitly_permitted"
            or "local" not in properties.get("llm_allowed_routes", [])):
        _fail("current source rights and correction status are not approved for local review")
    if batch.get("authority_note_sha256") != note_sha256:
        _fail("candidate was generated from a stale literature authority note")
    definition, definition_sha256 = _load_base_expert(batch.get("expert_id", ""))
    if (batch.get("expert_definition_version") != definition.get("definition_version") or
            batch.get("expert_definition_sha256") != definition_sha256):
        _fail("candidate was generated from a different expert definition")
    bundle = _build_bundle(batch, batch_bytes, manifest, extraction_path,
                           definition, definition_sha256, note_sha256,
                           authoritative_source, rights_review)
    payload = contracts.canonical_json(bundle)
    if destination.exists() or destination.is_symlink():
        try:
            if destination.is_file() and destination.read_bytes() == payload:
                return {"bundle_sha256": bundle["bundle_sha256"], "candidate_count": len(batch["candidates"]),
                        "output_sha256": hashlib.sha256(payload).hexdigest(), "reused": True}
        except OSError:
            pass
        _fail("candidate output already exists with different content")
    destination.parent.mkdir(parents=True, exist_ok=True)
    temp_path: Path | None = None
    try:
        fd, temp_name = tempfile.mkstemp(prefix=".p3-candidate-", dir=destination.parent)
        temp_path = Path(temp_name)
        with os.fdopen(fd, "wb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        if destination.exists() or destination.is_symlink():
            _fail("candidate output appeared during compilation")
        os.replace(temp_path, destination)
        temp_path = None
    finally:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)
    return {"bundle_sha256": bundle["bundle_sha256"], "candidate_count": len(batch["candidates"]),
            "output_sha256": hashlib.sha256(payload).hexdigest(), "reused": False}


def _loopback_endpoint(base_url: str) -> str:
    try:
        parsed = urllib.parse.urlsplit(base_url)
        hostname = parsed.hostname
        port = parsed.port
    except ValueError:
        _fail("candidate generation URL is invalid")
    if (parsed.scheme != "http" or hostname not in {"127.0.0.1", "localhost", "::1"}
            or parsed.username or parsed.password or parsed.query or parsed.fragment):
        _fail("candidate generation requires a loopback LM Studio URL")
    if hostname == "localhost":
        netloc = "127.0.0.1" if port is None else f"127.0.0.1:{port}"
        parsed = parsed._replace(netloc=netloc)
        base_url = urllib.parse.urlunsplit(parsed)
    return base_url.rstrip("/") if parsed.path.rstrip("/").endswith("/v1") else base_url.rstrip("/") + "/v1"


def _request_json(url: str, payload: dict | None = None, *, timeout: float) -> dict:
    data = None if payload is None else contracts.canonical_json(payload)
    request = urllib.request.Request(url, data=data,
                                     headers={"Accept": "application/json",
                                              "Content-Type": "application/json"},
                                     method="GET" if payload is None else "POST")
    class NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, req, fp, code, msg, headers, newurl):
            return None
    try:
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect)
        with opener.open(request, timeout=timeout) as response:
            raw = response.read(2 * 1024 * 1024 + 1)
        if len(raw) > 2 * 1024 * 1024:
            _fail("local model response exceeds the size limit")
        result = json.loads(raw.decode("utf-8"))
    except (urllib.error.URLError, TimeoutError, OSError, UnicodeDecodeError, json.JSONDecodeError):
        _fail("local model endpoint failed")
    if not isinstance(result, dict):
        _fail("local model response is invalid")
    return result


def _safe_output_bytes(path: Path, payload: bytes) -> dict:
    if path.exists() or path.is_symlink():
        _fail("candidate output appeared during inference")
    verified_target = _candidate_output_target(path)
    if verified_target != path:
        _fail("candidate output target changed during inference")
    path.parent.mkdir(parents=True, exist_ok=True)
    if _candidate_output_target(path) != path:
        _fail("candidate output parent changed before write")
    fd, temp_name = tempfile.mkstemp(prefix=".candidate-output-", dir=path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        if _candidate_output_target(path) != path:
            _fail("candidate output parent changed during write")
        if path.exists() or path.is_symlink():
            _fail("candidate output appeared during write")
        os.replace(temp_path, path)
        temp_path = None
    finally:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)
    return {"sha256": hashlib.sha256(payload).hexdigest(), "reused": False}


def _candidate_output_target(path: str | Path) -> Path:
    target = Path(path).expanduser().absolute()
    repository_root = Path(__file__).resolve().parents[3]
    resolved_target = target.resolve(strict=False)
    if resolved_target.is_relative_to(repository_root):
        _fail("candidate batch output may not be written inside the repository")
    if (target.exists() or target.is_symlink() or resolved_target.exists()
            or resolved_target.is_symlink()):
        _fail("candidate output path already exists; choose an unused versioned path")
    return resolved_target


def generate_gale_candidates_local(source_extraction_dir: str | Path,
                                   output_batch_path: str | Path, *,
                                   base_url: str = "http://127.0.0.1:1234/v1",
                                   timeout: float = 180.0) -> dict:
    """Generate a hash-bound pending Gale batch through loopback LM Studio only.

    The source page is sent only to the explicitly selected local runtime. The
    serialized output holds generated paraphrases and provenance hashes, never
    the source excerpt. The batch cannot create an approved Claim or Pack.
    """
    target = _candidate_output_target(output_batch_path)
    endpoint = _loopback_endpoint(base_url)
    extraction_path = Path(source_extraction_dir).expanduser().resolve(strict=True)
    if not extraction_path.is_dir() or extraction_path.is_symlink():
        _fail("source extraction directory is unavailable")
    manifest, manifest_bytes = _json_file(extraction_path / "manifest.json",
                                          MAX_EXTRACTION_MANIFEST_BYTES, canonical=True)
    manifest_hash = manifest.get("manifest_sha256")
    unsigned_manifest = {key: value for key, value in manifest.items() if key != "manifest_sha256"}
    if (not isinstance(manifest_hash, str) or contracts.sha256_json(unsigned_manifest) != manifest_hash
            or manifest.get("kind") != "private_source_extraction"):
        _fail("source extraction manifest is invalid")
    authoritative_source, rights_review, note_sha256 = source_ingestion._trusted_source_authority(P3_SOURCE_ID)
    note_source_without_anchors = {key: value for key, value in authoritative_source.items() if key != "anchors"}
    try:
        extracted_source = contracts.validate_source(manifest["source"])
    except (KeyError, contracts.ContractError):
        _fail("source extraction Source is invalid")
    extracted_source_without_anchors = {key: value for key, value in extracted_source.items() if key != "anchors"}
    if (extracted_source_without_anchors != note_source_without_anchors
            or manifest.get("rights_review") != rights_review
            or manifest.get("authority_note_sha256") != note_sha256
            or extracted_source["locator"]["kind"] == "local_uri"):
        _fail("source extraction does not match current Software Vault authority")
    if manifest.get("storage_class") != "private_local_only" or extracted_source["rights"]["allowed_routes"] != ["local"]:
        _fail("source extraction is not authorized for local-only processing")
    definition, definition_sha256 = _load_base_expert(P3_EXPERT_ID)
    excerpt_index = _load_excerpt_index(extraction_path / "excerpts.jsonl")
    anchor = next((item for item in extracted_source["anchors"] if item["anchor_id"] == GALE_ANCHOR_ID), None)
    if (anchor is None or anchor["kind"] != "page" or anchor["start"] != str(GALE_PDF_PAGE)
            or anchor["end"] != str(GALE_PDF_PAGE)):
        _fail("verified Gale PDF-to-printed page mapping is unavailable")
    excerpt = excerpt_index.get(anchor["extracted_text_sha256"])
    if excerpt is None or GALE_ANCHOR_ID not in excerpt["locations"]:
        _fail("verified Gale source excerpt is unavailable")

    models = _request_json(endpoint + "/models", timeout=5.0)
    model_rows = models.get("data")
    if not isinstance(model_rows, list) or not any(
            isinstance(row, dict) and row.get("id") == LOCAL_MODEL_ID for row in model_rows):
        _fail("pinned local model is not available in LM Studio")

    scope = {key: definition[key] for key in
             ("expert_id", "definition_version", "title", "scope", "out_of_scope",
              "required_inputs", "applicability_checks", "prohibited_conclusions")}
    source_binding = {"source_id": extracted_source["source_id"], "source_version": extracted_source["version"],
                      "source_sha256": extracted_source["sha256"], "source_manifest_sha256": manifest_hash,
                      "authority_note_sha256": note_sha256, "anchor_id": GALE_ANCHOR_ID,
                      "pdf_page": GALE_PDF_PAGE, "printed_page": GALE_PRINTED_PAGE,
                      "extracted_text_sha256": anchor["extracted_text_sha256"]}
    generation_template_hash = hashlib.sha256(GENERATION_PROMPT_TEMPLATE).hexdigest()
    request_descriptor = {
        "kind": "local_candidate_generation_request",
        "schema_version": 1,
        "model_id": LOCAL_MODEL_ID,
        "model_route": "local",
        "temperature": 0.1,
        "max_tokens": 1400,
        "expert_definition_sha256": definition_sha256,
        "expert_scope": scope,
        "source_binding": source_binding,
        "prompt_template_sha256": generation_template_hash,
        "response_schema_sha256": contracts.sha256_json(CANDIDATE_RESPONSE_SCHEMA),
    }
    user_prompt = _render_generation_prompt(_model_task_context(scope), excerpt["text"])
    rendered_prompt_hash = hashlib.sha256(user_prompt.encode("utf-8")).hexdigest()
    request_record = {**request_descriptor, "rendered_prompt_sha256": rendered_prompt_hash}
    generation_request_hash = contracts.sha256_json(request_record)
    payload = {
        "model": LOCAL_MODEL_ID,
        "messages": [
            {"role": "system", "content": "Return one JSON object with a candidates array only. All content is draft-only."},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.1,
        "max_tokens": 1400,
        "chat_template_kwargs": {"enable_thinking": False},
        "response_format": {"type": "json_schema", "json_schema": {
            "name": "gale_candidate_batch",
            "strict": True,
            "schema": CANDIDATE_RESPONSE_SCHEMA,
        }},
    }
    start_time = time.monotonic()
    result = _request_json(endpoint + "/chat/completions", payload, timeout=timeout)
    elapsed = time.monotonic() - start_time
    try:
        choice = result["choices"][0]
        message = choice["message"]
        raw_content = message["content"]
        usage = result["usage"]
        finish_reason = choice["finish_reason"]
    except (KeyError, IndexError, TypeError):
        _fail("local model returned an invalid candidate response")
    if not isinstance(usage, dict) or not isinstance(finish_reason, str):
        _fail("local model response metadata is invalid")
    if not isinstance(raw_content, str):
        _fail(f"local model content is not text (finish_reason={finish_reason})")
    token_counts = {key: usage.get(key) for key in ("prompt_tokens", "completion_tokens", "total_tokens")}
    if any(type(value) is not int or value < 0 for value in token_counts.values()):
        _fail(f"local model response lacks valid usage metadata (finish_reason={finish_reason})")
    if token_counts["total_tokens"] != token_counts["prompt_tokens"] + token_counts["completion_tokens"]:
        _fail(f"local model usage totals are inconsistent (finish_reason={finish_reason})")
    try:
        generated = json.loads(raw_content)
    except json.JSONDecodeError as exc:
        if finish_reason == "length":
            reason = "output_truncated"
        else:
            reason = "malformed_json"
        _fail(f"local model {reason} (finish_reason={finish_reason}; "
              f"prompt_tokens={token_counts['prompt_tokens']}; "
              f"completion_tokens={token_counts['completion_tokens']}; "
              f"total_tokens={token_counts['total_tokens']}; "
              f"elapsed_seconds={round(elapsed, 3)}; line={exc.lineno}; column={exc.colno})")
    if finish_reason != "stop" or not isinstance(generated, dict) or not isinstance(generated.get("candidates"), list):
        _fail(f"local model did not complete a valid candidate response (finish_reason={finish_reason}; "
              f"prompt_tokens={token_counts['prompt_tokens']}; completion_tokens={token_counts['completion_tokens']}; "
              f"total_tokens={token_counts['total_tokens']}; elapsed_seconds={round(elapsed, 3)})")
    candidate_rows = []
    try:
        for index, row in enumerate(generated["candidates"], start=1):
            normalized_row = _normalize_generated_candidate(row)
            candidate_rows.append({"candidate_id": f"gale-fw-{index:03d}", **normalized_row})
    except (CandidatePipelineError, contracts.ContractError) as exc:
        _fail(f"generated candidate rejected: {exc} (finish_reason={finish_reason}; "
              f"prompt_tokens={token_counts['prompt_tokens']}; "
              f"completion_tokens={token_counts['completion_tokens']}; "
              f"total_tokens={token_counts['total_tokens']}; elapsed_seconds={round(elapsed, 3)})")
    batch = {
        "kind": "unapproved_knowledge_candidate_batch", "schema_version": 1,
        "source_id": extracted_source["source_id"], "source_version": extracted_source["version"],
        "source_sha256": extracted_source["sha256"], "authority_note_sha256": note_sha256,
        "source_manifest_sha256": manifest_hash, "expert_id": P3_EXPERT_ID,
        "expert_definition_version": definition["definition_version"],
        "expert_definition_sha256": definition_sha256,
        "generation_request_sha256": generation_request_hash,
        "generation_prompt_template_sha256": generation_template_hash,
        "generation_prompt_sha256": rendered_prompt_hash,
        "generation_request_record": request_record,
        "generator": {"model": LOCAL_MODEL_ID, "runtime": "LM Studio loopback on local RTX 5070",
                      **token_counts, "elapsed_seconds": round(elapsed, 3),
                      "finish_reason": finish_reason, "temperature": 0.1},
        "review_status": "pending_human_review",
        "source_anchor": {"anchor_id": GALE_ANCHOR_ID, "pdf_page": GALE_PDF_PAGE,
                           "printed_page": GALE_PRINTED_PAGE,
                           "extracted_text_sha256": anchor["extracted_text_sha256"]},
        "candidates": candidate_rows,
        "promotion_gate": {"formal_claim_created": False, "approved_for_expert_pack": False,
                           "reason": "Human source review and evaluation are still required."},
    }
    try:
        _validate_batch(batch, [excerpt["text"]], expected_source_manifest_sha256=manifest_hash,
                        expected_expert_definition_sha256=definition_sha256,
                        expected_expert_scope=scope)
    except (CandidatePipelineError, contracts.ContractError) as exc:
        _fail(f"generated candidate batch rejected: {exc} (finish_reason={finish_reason}; "
              f"prompt_tokens={token_counts['prompt_tokens']}; "
              f"completion_tokens={token_counts['completion_tokens']}; "
              f"total_tokens={token_counts['total_tokens']}; elapsed_seconds={round(elapsed, 3)})")
    raw = contracts.canonical_json(batch)
    result_summary = _safe_output_bytes(target, raw)
    return {"candidate_count": len(candidate_rows), "review_status": batch["review_status"],
            "model": LOCAL_MODEL_ID, **token_counts, "elapsed_seconds": round(elapsed, 3),
            "generation_request_sha256": generation_request_hash,
            "source_manifest_sha256": manifest_hash, "expert_definition_sha256": definition_sha256,
            "batch_sha256": result_summary["sha256"], "reused": result_summary["reused"]}
