'use strict';
// Actual trusted templates + production scripts; all requests use offline fixtures.
const test=require('node:test');
const assert=require('node:assert/strict');
const {createHarness}=require('./harness.cjs');
const n=(h,id)=>h.document.getElementById(`analysis-history-${id}`);
const pending=(h,part)=>{const r=h.requests.findLast(x=>!x.settled&&x.url.includes(part));assert(r,part);return r;};
const run=(id='R1')=>({run_id:id,item_id:'A',status:'completed',question:`Question ${id}`,created_at:'2026-10-04T00:00:00Z',updated_at:'2026-10-04T00:10:00Z',source_revision:2,input_hash:'synthetic-hash',current_summary:'Synthetic integration',summary_annotation_version:1,summary_entry_id:'decision:D1'});
const entry=(id='label:L1',overrides={})=>({entry_id:id,kind:'label',title:'Synthetic label change',role:'handler',operation:'update',disposition:'adopt',status:'committed',annotation_version:2,before_annotation_version:1,after_annotation_version:2,utterance_id:'u:1',field:'label',reason:'Recorded reasoning',...overrides});
const page=(id='R1',overrides={})=>({run:run(id),versions:{initial:0,selected:2,latest:2,available:[0,1,2]},audit:{status:'partial',message:'Some legacy fields unavailable'},entries:[entry()],pagination:{limit:30,offset:0,total:1,has_more:false},...overrides});
const detail=(id='label:L1',overrides={})=>({entry:entry(id,{before_value:'before',after_value:'after',before_present:true,after_present:true,evidence_ids:['e1'],missing_fields:['model']}),evidence:[{evidence_id:'e1',utterance_id:'u:1',speaker:'Synthetic speaker'}],evidence_pagination:{offset:0,limit:30,total:1,has_more:false},...overrides});
async function setup(t,{open=true}={}){const h=await createHarness();t.after(()=>h.close());h.fixture({itemId:'A',data:{item:{id:'A',source_name:'Synthetic conversation',revision_count:2,analysis_revision:3},segments:[]},config:{},annotations:{},dirty:false});h.evaluate('Object.assign(analysisState,window.fixture);analysisCard.hidden=false;document.body.dataset.view="analysis"');if(open){h.click('#analysis-history-open');h.reply(pending(h,'/orchestration/viewer?'),{runs:[run(),run('R2')],pagination:{offset:0,total:2,has_more:false}});await h.flush();h.reply(pending(h,'/R1/viewer?'),page());await h.flush();}return h;}
function allReads(h){assert.equal(h.requests.filter(r=>(r.options.method||'GET')!=='GET').length,0);assert.equal(h.blocked.length,0);}
async function openEntry(h,id='label:L1',fixture=detail(id)){h.click(n(h,'timeline').querySelector(`[data-entry-id="${id}"]`));const r=pending(h,'/entries/');assert.match(r.url,/annotation_version=2/);h.reply(r,fixture);await h.flush();return r;}

test('visible read-only entry navigates runs, versions, details and fixed original by exact ID without POST',async t=>{
 const h=await setup(t);assert.equal(n(h,'dialog').open,true);assert.match(n(h,'target').textContent,/Synthetic conversation/);assert.match(n(h,'version-note').textContent,/初期 v0.*最新 v2/);assert.match(n(h,'summary-title').textContent,/作成時ラベル v1/);
 await openEntry(h);assert.match(n(h,'detail').textContent,/before/);assert.match(n(h,'detail').textContent,/Recorded reasoning/);assert.match(n(h,'detail').textContent,/採用/);
 h.click([...n(h,'detail').querySelectorAll('button')].find(b=>b.textContent.startsWith('固定原文')));const r=pending(h,'/sources/u%3A1');assert.match(r.url,/annotation_version=2/);
 h.reply(r,{source:{utterance_id:'u:1',text:'Immutable synthetic original',speaker:'S1',start:0,end:1,excluded:false,source_hash:'fixed'},labels:{initial:{label:'initial'},selected:{label:'selected'},latest:{label:'latest'}},versions:{initial:0,selected:2,latest:2},provenance:{item_id:'A',run_id:'R1',initial_id:'I1',input_hash:'H1'},audit:{message:'fixed'}});await h.flush();assert.match(n(h,'source').textContent,/Immutable synthetic original/);assert.match(n(h,'source').textContent,/初期ラベル.*選択版ラベル.*最新ラベル/s);
 h.change(n(h,'version'),'0');assert.match(pending(h,'/R1/viewer?').url,/annotation_version=0/);h.reply(pending(h,'/R1/viewer?'),page('R1',{versions:{initial:0,selected:0,latest:2,available:[0,1,2]}}));await h.flush();assert.equal(n(h,'detail').querySelector('blockquote'),null);allReads(h);
});

test('timeline filters, UTF-safe params, numeric past versions and page controls use bounded GETs',async t=>{
 const h=await setup(t);h.change(n(h,'kind'),'label');h.change(n(h,'role'),'handler');h.change(n(h,'operation'),'delete');h.change(n(h,'status'),'committed');h.change(n(h,'after'),'2026-10-01');h.change(n(h,'before'),'2026-10-04');h.click(n(h,'filters').querySelector('[type="submit"]'));
 let r=pending(h,'/R1/viewer?'),q=new URL(r.url,'https://gurumoji.invalid').searchParams;assert.equal(q.get('status'),'committed');assert.equal(q.get('operation'),'delete');assert.equal(q.get('after'),'2026-10-01T00:00:00Z');assert.equal(q.get('before'),'2026-10-04T23:59:59.999999Z');
 h.reply(r,page('R1',{pagination:{offset:0,limit:30,total:45,has_more:true},versions:{initial:0,selected:2,latest:301,available:[0,1,2,301],has_more:true}}));await h.flush();assert.equal(n(h,'version-form').hidden,false);h.click(n(h,'next'));r=pending(h,'/R1/viewer?');assert.match(r.url,/offset=30/);h.reply(r,page('R1',{pagination:{offset:30,limit:30,total:45,has_more:false},versions:{initial:0,selected:2,latest:301,available:[0,1,2,301],has_more:true}}));await h.flush();assert.equal(n(h,'prev').disabled,false);
 // A large history can address a version not in the first dropdown page.
 h.change(n(h,'version-number'),'217');h.click(n(h,'version-form').querySelector('[type="submit"]'));r=pending(h,'/R1/viewer?');assert.match(r.url,/annotation_version=217/);h.reply(r,page('R1',{versions:{initial:0,selected:217,latest:301,available:[0,1,2,301],has_more:true}}));await h.flush();assert.equal(n(h,'version').value,'217');allReads(h);
});

test('all API strings remain literal, missing provenance stays unrecorded, and proposal differs from delete',async t=>{
 const h=await setup(t),attack='<img src=x onerror="window.bad=1">';await openEntry(h,'label:L1',detail('label:L1',{entry:entry('label:L1',{title:attack,summary:attack,model:attack,reason:null,status:'proposed',disposition:'proposal',before_value:null,after_value:{label:attack},claims:[{text:attack}],evidence_ids:[attack],missing_fields:['reason'],before_present:undefined,proposed_value:'SYNTHETIC PROPOSAL'})}));
 assert.match(n(h,'detail').textContent,/提案です/);assert.match(n(h,'detail').textContent,/提案値（採用された値とは別の記録）/);assert.match(n(h,'detail').textContent,/SYNTHETIC PROPOSAL/);assert.match(n(h,'detail').textContent,/未記録/);assert(n(h,'detail').textContent.includes(attack));assert.equal(n(h,'detail').querySelectorAll('img,svg,script').length,0);assert.equal(h.w.bad,undefined);
 h.click(n(h,'timeline').querySelector('button'));h.reply(pending(h,'/entries/'),detail('label:L1',{entry:entry('label:L1',{operation:'delete',tombstone:true,before_value:'old',after_value:null})}));await h.flush();assert.match(n(h,'detail').textContent,/削除済み（履歴を保持）/);assert.doesNotMatch(h.w.localStorage.getItem('private')||'',/old/);allReads(h);
});

test('detail and source reads are latest-wins, closed dialogs reject late private data and reopen has an ABA fence',async t=>{
 const h=await setup(t);h.click(n(h,'timeline').querySelector('button'));const old=pending(h,'/entries/');h.click(n(h,'summary-links').querySelector('button'));const newest=pending(h,'/entries/decision%3AD1');h.reply(newest,detail('decision:D1',{entry:entry('decision:D1',{title:'New chosen detail'})}));await h.flush();h.reply(old,detail('label:L1',{entry:entry('label:L1',{title:'Stale detail'})}));await h.flush();assert.match(n(h,'detail').textContent,/New chosen detail/);assert.doesNotMatch(n(h,'detail').textContent,/Stale detail/);
 h.click([...n(h,'detail').querySelectorAll('button')].find(b=>b.textContent.startsWith('固定原文')));const source=pending(h,'/sources/');h.click(n(h,'close'));h.click('#analysis-history-open');const list=pending(h,'/orchestration/viewer?');h.reply(source,{source:{utterance_id:'u:1',text:'LATE PRIVATE'},provenance:{item_id:'A',run_id:'R1'}});await h.flush();assert.doesNotMatch(n(h,'dialog').textContent,/LATE PRIVATE/);h.reply(list,{runs:[],pagination:{total:0,offset:0,has_more:false}});await h.flush();allReads(h);
});

test('R1 to R2 to R1 responses cannot populate the newer selection; navigation closes and fences reads',async t=>{
 const h=await setup(t);h.click(n(h,'refresh'));const old=pending(h,'/R1/viewer?');h.click(n(h,'run-list').querySelector('[data-run-id="R2"]'));const r2=pending(h,'/R2/viewer?');h.click(n(h,'run-list').querySelector('[data-run-id="R1"]'));const newR1=pending(h,'/R1/viewer?');h.reply(newR1,page('R1',{run:{...run(),current_summary:'Newest R1'}}));await h.flush();h.reply(r2,page('R2'));h.reply(old,page('R1',{run:{...run(),current_summary:'Stale R1'}}));await h.flush();assert.equal(n(h,'summary').textContent,'Newest R1');
 h.click(n(h,'refresh'));const late=pending(h,'/R1/viewer?');h.click('#show-library-button');assert.equal(n(h,'dialog').open,false);h.reply(late,page('R1',{run:{...run(),current_summary:'LATE NAVIGATION'}}));await h.flush();assert.doesNotMatch(n(h,'dialog').textContent,/LATE NAVIGATION/);allReads(h);
});

test('evidence pages expose fixed originals beyond first 30; 404s never fall back to live editor',async t=>{
 const h=await setup(t);await openEntry(h,'label:L1',detail('label:L1',{evidence_pagination:{offset:0,limit:30,total:65,has_more:true}}));h.click([...n(h,'detail').querySelectorAll('button')].find(b=>b.textContent==='次の根拠'));const r=pending(h,'/entries/');assert.match(r.url,/evidence_offset=30/);h.reply(r,detail('label:L1',{evidence:[{utterance_id:'u:31',speaker:'S2'}],evidence_pagination:{offset:30,limit:30,total:65,has_more:true}}));await h.flush();h.click([...n(h,'detail').querySelectorAll('button')].find(b=>b.textContent.startsWith('固定原文 u:31')));h.reply(pending(h,'/sources/u%3A31'),{},404);await h.flush();assert.match(n(h,'source').textContent,/HTTP 404/);assert.equal(h.w.location.hash,'#/new');allReads(h);
});

test('slides wait for explicit design save, bind snapshot, render safely and offer one pinned PPTX GET link',async t=>{
 const h=await setup(t);h.click(n(h,'tab-slides'));h.reply(pending(h,'/slides/templates'),{snapshot_signature:'snap1',templates:[{id:'research',name:'Research',version:'1',description:'Sample',design:{layout:'Plain'},prompt:'Use only saved facts'}],design:null});await h.flush();assert.equal(n(h,'slide-preview').disabled,true);assert.equal(n(h,'slide-download').hidden,true);allReads(h);
 h.click(n(h,'slide-save'));const save=pending(h,'/slides/design');assert.equal(save.options.method,'POST');assert.deepEqual(JSON.parse(save.options.body),{template:'research',expected_snapshot:'snap1'});h.click(n(h,'slide-save'));assert.equal(h.requests.filter(r=>r.options.method==='POST').length,1);h.reply(save,{snapshot_signature:'snap1',design:{template_id:'research',template_version:'1',snapshot_signature:'snap1',design_hash:'D1'}});await h.flush();assert.equal(n(h,'slide-preview').disabled,false);
 h.click(n(h,'slide-preview'));const preview=pending(h,'/slides/preview');assert.match(preview.url,/expected_snapshot=snap1/);h.reply(preview,{template:{id:'research',name:'Research',version:'1'},snapshot_signature:'snap1',provenance:{item_id:'A',run_id:'R1',annotation_version:2},slides:[{title:'<img onerror=evil()>',paragraphs:['<svg onload=evil()>'],evidence_ids:['u:1'],result_ids:[],notes:'source facts'}],warnings:[],download:{available:true}});await h.flush();assert.equal(n(h,'slide-content').querySelectorAll('img,svg').length,0);assert.match(n(h,'slide-download').getAttribute('href'),/\/R1\/slides\/presentation\.pptx\?template=research&expected_snapshot=snap1$/);assert.equal(h.requests.filter(r=>r.options.method==='POST').length,1);
});

test('stale slide receipt cannot enable preview; failed save keeps export disabled',async t=>{
 const h=await setup(t);h.click(n(h,'tab-slides'));h.reply(pending(h,'/slides/templates'),{snapshot_signature:'new',templates:[{id:'research',name:'Research',version:'1'}],design:{template_id:'research',design_hash:'old',matches_snapshot:false}});await h.flush();assert.equal(n(h,'slide-preview').disabled,true);h.click(n(h,'slide-save'));h.reply(pending(h,'/slides/design'),{},409);await h.flush();assert.equal(n(h,'slide-preview').disabled,true);assert.equal(n(h,'slide-download').hidden,true);assert.match(n(h,'slide-status').textContent,/HTTP 409/);assert.equal(h.requests.filter(r=>r.url.includes('/slides/preview')).length,0);
});

test('wrong fixed-source version and mismatched slide snapshot cannot publish text or a download link',async t=>{
 const h=await setup(t);await openEntry(h);h.click([...n(h,'detail').querySelectorAll('button')].find(b=>b.textContent.startsWith('固定原文')));h.reply(pending(h,'/sources/'),{source:{utterance_id:'u:1',text:'Wrong version original'},versions:{selected:1},provenance:{item_id:'A',run_id:'R1'}});await h.flush();assert.match(n(h,'source').textContent,/ラベル版が一致しません/);assert.doesNotMatch(n(h,'source').textContent,/Wrong version original/);
 h.click(n(h,'tab-slides'));h.reply(pending(h,'/slides/templates'),{snapshot_signature:'snap1',templates:[{id:'research',name:'Research',version:'1'}],design:{template_id:'research',design_hash:'D1',snapshot_signature:'snap1',matches_snapshot:true}});await h.flush();h.click(n(h,'slide-preview'));h.reply(pending(h,'/slides/preview'),{template:{id:'research'},snapshot_signature:'DIFFERENT',provenance:{item_id:'A',run_id:'R1'},slides:[{title:'Wrong snapshot result'}],download:{available:true}});await h.flush();assert.match(n(h,'slide-status').textContent,/対象・保存版を確認できません/);assert.equal(n(h,'slide-download').hidden,true);assert.equal(n(h,'slide-download').hasAttribute('href'),false);assert.doesNotMatch(n(h,'slide-content').textContent,/Wrong snapshot result/);allReads(h);
});

test('source truncation is visible and late slide catalog is discarded after changing run',async t=>{
 const h=await setup(t);await openEntry(h);h.click([...n(h,'detail').querySelectorAll('button')].find(b=>b.textContent.startsWith('固定原文')));h.reply(pending(h,'/sources/'),{source:{utterance_id:'u:1',text:'Partial synthetic source',text_truncated:true},versions:{selected:2},provenance:{item_id:'A',run_id:'R1'},truncated_fields:['labels.selected.codes']});await h.flush();assert.match(n(h,'source').textContent,/全文ではありません/);assert.match(n(h,'source').textContent,/labels.selected.codes/);
 h.click(n(h,'tab-slides'));const late=pending(h,'/slides/templates');h.click(n(h,'run-list').querySelector('[data-run-id="R2"]'));h.reply(pending(h,'/R2/viewer?'),page('R2'));await h.flush();h.reply(late,{snapshot_signature:'old',templates:[{id:'research',name:'Stale private template',version:'1'}]});await h.flush();assert.doesNotMatch(n(h,'slides').textContent,/Stale private template/);allReads(h);
});

test('proposal stated old value is separate from unchanged actual values and unknown legacy application',async t=>{
 const h=await setup(t);await openEntry(h,'label:L1',detail('label:L1',{entry:entry('label:L1',{disposition:'proposal',status:'proposed',before_value:'ACTUAL BASE',after_value:'ACTUAL BASE',before_present:true,after_present:true,stated_old_value:'FALSE STATED OLD',proposed_value:'NEW PROPOSAL'})}));
 assert.match(n(h,'detail').textContent,/提案が申告した変更前値（実値とは別）/);assert.match(n(h,'detail').textContent,/FALSE STATED OLD/);assert.match(n(h,'detail').textContent,/NEW PROPOSAL/);
 const actual=n(h,'detail').querySelector('.analysis-history-before-after');assert.equal(actual.querySelectorAll('pre')[0].textContent,'ACTUAL BASE');assert.equal(actual.querySelectorAll('pre')[1].textContent,'ACTUAL BASE');assert.doesNotMatch(actual.textContent,/FALSE STATED OLD|NEW PROPOSAL/);
 h.click(n(h,'timeline').querySelector('button'));h.reply(pending(h,'/entries/'),detail('label:L1',{entry:entry('label:L1',{kind:'legacy_label',disposition:'proposal',status:'proposed',before_value:null,after_value:null,before_present:null,after_present:null,stated_old_value:'LEGACY STATED OLD',proposed_value:'LEGACY PROPOSAL',missing_fields:['applied_before_value','applied_after_value']})}));await h.flush();
 const legacy=n(h,'detail').querySelector('.analysis-history-before-after');assert.equal(legacy.querySelectorAll('pre')[0].textContent,'未記録');assert.equal(legacy.querySelectorAll('pre')[1].textContent,'未記録');assert.match(n(h,'detail').textContent,/LEGACY STATED OLD/);assert.match(n(h,'detail').textContent,/LEGACY PROPOSAL/);assert.doesNotMatch(legacy.textContent,/LEGACY/);allReads(h);
});
